# app/voice_engine/tts_client.py
import os
import aiohttp
import logging
from typing import AsyncGenerator

logger = logging.getLogger(__name__)

class CartesiaStreamingClient:
    """
    Handles chunk-by-chunk binary audio generation directly from 
    streaming string tokens generated by Padi.
    """
    def __init__(self):
        # Read API Key from local execution environment safely
        self.api_key = os.getenv("CARTESIA_API_KEY", "mock_key_if_unassigned")
        self.tts_url = "https://api.cartesia.ai/v1/audio/stream"
        
    async def stream_text_to_voice(self, text_generator: AsyncGenerator[str, None]) -> AsyncGenerator[bytes, None]:
        """
        Consumes text tokens sequentially and pipes them into a chunked HTTP POST
        response stream, yielding raw playable 16kHz linear PCM audio bytes.
        """
        headers = {
            "X-API-Key": self.api_key,
            "Content-Type": "application/json",
            "Cartesia-Version": "2024-06-10"
        }

        async with aiohttp.ClientSession() as session:
            async for text_token in text_generator:
                # Construct Cartesia Sonic payload format optimized for real-time applications
                payload = {
                    "model_id": "sonic-english",
                    "transcript": text_token,
                    "voice": {
                        "mode": "id",
                        "id": "embed://padi-friendly-agent" # Target custom voice architecture signature
                    },
                    "output_format": {
                        "container": "raw",
                        "encoding": "pcm_16le",
                        "sample_rate": 16000
                    }
                }
                
                try:
                    async with session.post(self.tts_url, headers=headers, json=payload) as response:
                        if response.status != 200:
                            err_body = await response.text()
                            logger.error(f"Cartesia Voice Stream failure code {response.status}: {err_body}")
                            yield b""
                            continue
                            
                        # Chunk the incoming voice bytes into 1024-byte packets for instant delivery
                        async for chunk in response.content.iter_chunked(1024):
                            yield chunk
                except Exception as e:
                    logger.error(f"Exception triggered in Cartesia socket pipe formatting: {str(e)}")
                    yield b""